config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    delete 'sign_out', to: 'users/sessions#destroy'

    get 'forgot_password', to: 'users/passwords#new'
    get 'reset_password', to: 'users/passwords#edit'
  end

  root 'welcome#index'

  get 'dashboard', to: 'dashboard#index'

  get 'about', to: 'welcome#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_in_path_for(_resource)
    dashboard_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/flash_helper.rb
module FlashHelper

  def flash_class(level)
    case level
    when 'notice' then 'bg-blue-50 border border-blue-100'
    when 'success' then 'bg-green-50 border border-green-100'
    when 'error' then 'bg-red-50 border border-red-100'
    when 'alert' then 'bg-yellow-50 border border-yellow-100'
    end
  end

  # ( I used gem 'inline_svg' to handle svgs within my app and Zondicons for the svg's)

  def flash_icon(img)
    case img
      when 'notice' then "information-outline.svg" # Zondicons
      when 'success' then "checkmark-outline.svg" # Zondicons
      when 'error' then "exclamation-outline.svg" # Zondicons
      when 'alert' then "close-outline.svg" # Zondicons
    end
  end

  def flash_status(status)
    case status
      when 'notice' then content_tag :p, "My App - Notice", class: "font-bold text-xl text-blue-500"
      when 'success' then content_tag :p, "My App - Success", class: "font-bold text-xl text-green-500"
      when 'error' then content_tag :p, "My App - Warning", class: "font-bold text-xl text-red-500"
      when 'alert' then content_tag :p, "My App - Error", class: "font-bold text-xl text-yellow-500"
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/index.html.erb
<%= render "dashboard/shared/sidebar" do %>
  <h1>Logged in</h1>
<% end %>

app/views/dashboard/shared/_sidebar.html.erb
<div class="h-screen flex overflow-hidden bg-gray-100">
  <!-- Off-canvas menu for mobile, show/hide based on off-canvas menu state. -->
  <div class="md:hidden hidden" id="mdMenu">
    <div class="fixed inset-0 flex z-40">
      <!--
        Off-canvas menu overlay, show/hide based on off-canvas menu state.

        Entering: "transition-opacity ease-linear duration-300"
          From: "opacity-0"
          To: "opacity-100"
        Leaving: "transition-opacity ease-linear duration-300"
          From: "opacity-100"
          To: "opacity-0"
      -->
      <div class="fixed inset-0">
        <div class="absolute inset-0 bg-gray-600 opacity-75" id="overlay"></div>
      </div>
      <!--
        Off-canvas menu, show/hide based on off-canvas menu state.

        Entering: "transition ease-in-out duration-300 transform"
          From: "-translate-x-full"
          To: "translate-x-0"
        Leaving: "transition ease-in-out duration-300 transform"
          From: "translate-x-0"
          To: "-translate-x-full"
      -->
      <div class="relative flex-1 flex flex-col max-w-xs w-full bg-white">
        <div class="absolute top-0 right-0 -mr-14 p-1">
          <button class="flex items-center justify-center h-12 w-12 rounded-full focus:outline-none focus:bg-gray-600" aria-label="Close sidebar" onclick="document.getElementById('mdMenu').classList.add('hidden');">
            <svg class="h-6 w-6 text-gray-600" stroke="currentColor" fill="none" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
            </svg>
          </button>
        </div>
        <div class="flex-1 h-0 pt-5 pb-4 overflow-y-auto">
          <div class="flex-shrink-0 flex items-center px-4 text-blue-500">
            <a href="/" alt="home" class="flex items-center">
              <img class="h-8 w-auto rounded mr-2" src="/small_logo.png" alt="acornchat.com logo">
              acornchat.com
            </a>
          </div>

          <nav class="mt-5 px-2 space-y-1">


            <a href="/" class="group flex items-center px-2 py-2 text-base leading-6 font-medium rounded-md text-gray-900 bg-gray-100 focus:outline-none focus:bg-gray-200 transition ease-in-out duration-150">
              <!-- Heroicon name: home -->
              <svg class="mr-4 h-6 w-6 text-gray-400 group-hover:text-gray-500 group-focus:text-gray-600 transition ease-in-out duration-150" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path>
              </svg>
              Home
            </a>

          </nav>
        </div>
        <div class="flex-shrink-0 flex border-t border-gray-200 p-4 flex-col">

          <div class="flex-shrink-0 group block">
            <div class="flex items-center">

              <div class="text-sm font-medium text-blue-500 hover:text-blue-700 flex flex-col justify-center items-center">
                <img class="inline-block h-8 w-8 rounded-full" src="/images/member.png" alt="">
              </div>


              <a href="/profile" class="ml-3">
                <p class="text-sm leading-5 font-medium text-gray-500 group-hover:text-gray-700 transition ease-in-out duration-150">
                  View profile
                </p>
              </a>
            </div>
          </div>



          <div class="group flex items-center px-2 py-2 mt-4 text-base leading-6 font-medium text-gray-600 rounded-md hover:text-gray-900 hover:bg-gray-50 focus:outline-none focus:text-gray-900 focus:bg-gray-100 transition ease-in-out duration-150">
            <svg class="mr-4 h-6 w-6 text-gray-400 group-hover:text-gray-500 group-focus:text-gray-500 transition ease-in-out duration-150" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
            </svg>
            <%= link_to "Sign out", sign_out_path, method: :delete %>
          </div>
        </div>
      </div>
      <div class="flex-shrink-0 w-14">
        <!-- Force sidebar to shrink to fit close icon -->
      </div>
    </div>
  </div>
  <!-- Static sidebar for desktop -->
  <div class="hidden md:flex md:flex-shrink-0">
    <div class="flex flex-col w-64">
      <!-- Sidebar component, swap this element with another sidebar if you like -->
      <div class="flex flex-col h-0 flex-1 border-r border-gray-200 bg-white">
        <div class="flex-1 flex flex-col pt-5 pb-4 overflow-y-auto">
          <a href="/" class="flex items-center flex-shrink-0 px-4 text-blue-500">
            <img class="h-8 w-auto mr-2 rounded" src="/small_logo.png" alt="acornchat.com logo">
            acornchat.com
          </a>

          <nav class="mt-5 flex-1 px-2 space-y-1 bg-white">
            <div class="group flex items-center px-2 py-2 text-sm leading-5 font-medium rounded-md text-gray-900 bg-gray-100 hover:text-gray-900 hover:bg-gray-100 focus:outline-none focus:bg-gray-200 transition ease-in-out duration-150">
              <!-- Heroicon name: home -->
              <svg class="mr-3 h-6 w-6 text-gray-400 group-hover:text-gray-500 group-focus:text-gray-600 transition ease-in-out duration-150" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path>
              </svg>
              <%= link_to "Home", dashboard_path %>
            </div>
          </nav>
        </div>
        <div class="flex flex-col flex-shrink-0 border-t border-gray-200 p-4">
          <div class="flex-shrink-0 group block">
            <div class="flex items-center">
              <div class="text-sm font-medium text-blue-500 hover:text-blue-700 flex flex-col justify-center items-center">
                <img class="inline-block h-8 w-8 rounded-full" src="/images/member.png" alt="">
              </div>

              <a href="/profile" class="ml-3">
                <p class="text-sm leading-5 font-medium text-gray-500 group-hover:text-gray-700 transition ease-in-out duration-150">
                  View profile
                </p>
              </a>
            </div>
          </div>

          <div class="group flex items-center px-2 py-2 mt-4 text-base leading-6 font-medium text-gray-600 rounded-md hover:text-gray-900 hover:bg-gray-50 focus:outline-none focus:text-gray-900 focus:bg-gray-100 transition ease-in-out duration-150">
            <svg class="mr-4 h-6 w-6 text-gray-400 group-hover:text-gray-500 group-focus:text-gray-500 transition ease-in-out duration-150" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
            </svg>
            <%= link_to "Sign out", sign_out_path, method: :delete %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="flex flex-col w-0 flex-1 overflow-hidden">
    <div class="md:hidden pl-1 pt-1 sm:pl-3 sm:pt-3">
      <button class="-ml-0.5 -mt-0.5 h-12 inline-flex items-center justify-center rounded-md text-gray-500 hover:text-gray-900 focus:outline-none focus:bg-gray-200 transition ease-in-out duration-150" aria-label="Open sidebar" onclick="document.getElementById('mdMenu').classList.remove('hidden');">
        <!-- Heroicon name: menu hamburger -->
        <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
        </svg>
        <span class="ml-2"></span>
      </button>
    </div>
    <main id="main" class="flex-1 relative z-0 overflow-y-auto focus:outline-none" tabindex="0">
      <div class="p-4 border-b border-gray-300 bg-white flex justify-between items-center">
        <div class="flex">
          <h1 class="text-lg leading-6 font-medium text-gray-900">Home</h1>
        </div>
      </div>

      <div class="flex flex-row flex-wrap justify-start">
        <div class="pt-2 pb-6 md:py-6 w-full flex-grow" style="max-width: 700px;">
          <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 lg:mr-0 lg:pr-0">
            <%= yield %>
          </div>
        </div>
<!--        <div class="m-8 mt-0 lg:mt-8 lg:mr-0 lg:pr-8 pt-2 flex-grow max-w-7xl xl:max-w-xs" style="max-width: 700px;">-->

<!--        </div>-->
      </div>
    </main>
  </div>
</div>

<script type="text/javascript">
    const overlay = document.getElementById('overlay');
    const mdMenu = document.getElementById('mdMenu');

    overlay.addEventListener('click', (_event) => mdMenu.classList.add('hidden'));
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Acornchat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:creator" content="@acornchat">
    <meta name="twitter:title" content="AcornChat">
    <meta name="twitter:description" content="Live customer chat for entrepreneurs and small teams">
    <meta name="twitter:image" content="https://acornchat.com/twitter.png">

    <meta property="twitter:widgets:csp" content="on">

    <meta property="og:image" content="https://acornchat.com/twitter.png">
    <meta property="og:type" content="website">
    <meta property="og:title" content="AcornChat">
    <meta property="og:description" content="Live customer chat for entrepreneurs and small teams">
    <meta property="og:url" content="https://acornchat.com">
  </head>

  <body>
    <%= render partial: "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <div class="fixed inset-0 flex flex-col items-end px-4 py-6 pointer-events-none sm:p-6 sm:items-end sm:justify-start z-50" data-flash-notifications='true'>

    <% flash.each do |msg_type, msg| %>
      <div class="<%= flash_class(msg_type) %> max-w-sm w-full mt-2 bg-white shadow-lg rounded-lg pointer-events-auto transition-transform transform ease-in-out duration-300">
        <div class="rounded-lg shadow-xs overflow-hidden">
          <div class="p-4">
            <div class="flex items-start">
              <div class="flex-shrink-0">
                <svg class="h-6 w-6 text-gray-400"
                     viewBox="0 0 24 24" stroke="currentColor"
                     <% if msg_type == 'notice' %>
                     style="color: #4299E1;"
                     <% elsif msg_type == 'success' %>
                     style="color: #68D391;"
                     <% elsif msg_type == 'error' %>
                     style="color: #FC8181;"
                     <% elsif msg_type == 'alert' %>
                     style="color: #F6E05E;"
                     <% end %>>
                  <path <% if msg_type == 'notice' %> class="text-blue-400" <% end %>
                        <% if msg_type == 'success' %> class="text-green-400" <% end %>
                        <% if msg_type == 'alert' %> class="text-yellow-300" <% end %>
                        <% if msg_type == 'error' %> class="text-red-500" <% end %>
                        stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="<% if msg == 'notice' %>M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z
                          <% elsif msg_type == 'success' %>M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z
                          <% elsif msg_type == 'alert' %>M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z
                          <% elsif msg_type == 'error' %>M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z
                          <% end %>" />
                </svg>
              </div>
              <div class="ml-3 w-0 flex-1 pt-0.5">
                <p class="text-sm leading-5 font-medium text-gray-900">
                  <%= msg %>
                </p>
              </div>
              <div class="ml-4 flex-shrink-0 flex">
                <button onclick="this.closest('.transition-transform').classList.add('scale-0'); setTimeout(() => { this.closest('.transition-transform').classList.add('hidden'); }, 300);"
                        class="inline-flex text-gray-400 focus:outline-none focus:text-gray-500 transition ease-in-out duration-150">
                  <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd"
                          d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                          clip-rule="evenodd" />
                  </svg>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<%= render "welcome/shared/layout" do %>
  <main class="mt-16 mx-auto max-w-7xl px-4 sm:mt-24">
    <div class="text-center">
      <h1 class="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
        <span class="block xl:inline">Live chat widget</span>
      </h1>
      <h1 class="text-blue-600 xl:inline text-xl sm:text-2xl md:text-3xl font-bold">
        <span class="text-gray-400 font-medium">for</span>
        bootstrappers
        <span class="text-gray-400 font-medium">and</span>
        small teams
      </h1>
      <p class="mt-3 max-w-md mx-auto text-bas text-gray-500 sm:text-lg md:mt-5 md:text-xl md:max-w-3xl">
        Chat with your website visitors directly in Slack. Works around your schedule.
      </p>
    </div>

    <div class="flex items-center justify-center mt-8">
      <img src="./slack_acorn.png" style="height: 80px;" />
    </div>

    <div class="flex flex-col items-center justify-center my-8 sm:flex-row">
      <label for="email" class="sr-only">
        Email address
      </label>
      <input
        type="email"
        name="email"
        id="email"
        class="w-full px-5 py-3 border border-gray-300 shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 sm:max-w-xs rounded-md"
        placeholder="Enter your email"
      />
      <button
        type="submit"
        class="w-full mt-2 px-5 py-3 border border-transparent rounded-md text-white bg-blue-600 shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 sm:mt-0 sm:ml-3 sm:w-auto sm:flex-shrink-0">
        Get notified
      </button>
    </div>
  </main>
<% end %>

app/views/welcome/shared/_navbar.html.erb
<div class="hidden sm:block max-w-7xl mx-auto px-4 sm:px-6">
  <nav class="relative flex items-center justify-between sm:h-10 md:justify-center" aria-label="Global">
    <div class="flex items-center flex-1 md:absolute md:inset-y-0 md:left-0">
      <div class="flex items-center justify-between w-full md:w-auto">
        <a href="/">
          <span class="sr-only">Acorn Chat</span>
          <img class="h-8 w-auto sm:h-10" src="/small_logo.png" alt="Logo">
        </a>
        <div class="-mr-2 flex items-center md:hidden">
          <button type="button" class="bg-gray-50 rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-blue-500" id="main-menu" aria-haspopup="true">
            <span class="sr-only">Open main menu</span>
            <!-- Heroicon name: outline/menu -->
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
            </svg>
          </button>
        </div>
      </div>
    </div>
    <div class="hidden md:flex md:space-x-10">
    </div>
    <div class="hidden md:absolute md:flex md:items-center md:justify-end md:inset-y-0 md:right-0">
      <a class="mr-4 text-md text-blue-900 rounded py-1 px-2 hover:underline" href="/#how_it_works">How It Works</a>

      <a class="mr-4 text-md text-blue-900 rounded py-1 px-2 hover:underline" href="/#pricing">Pricing</a>

      <% if current_user %>
        <%= link_to current_user.email, dashboard_path, class: "mr-4 text-md text-blue-900 rounded py-1 px-2 hover:underline" %>

        <%= link_to "Sign out", sign_out_path, method: :delete, class: "mr-4 text-md text-blue-900 rounded py-1 px-2 hover:underline" %>
      <% else %>
        <%= link_to "Sign Up", sign_up_path, class: "mr-4 text-md text-blue-900 rounded py-1 px-2 hover:underline" %>

        <%= link_to "Login", sign_in_path, class: "text-lg text-blue-500 border border-2 border-blue rounded py-1 px-2 border-blue-500 hover:bg-blue-500 hover:text-white hover:shadow bg-white" %>
      <%end%>
    </div>
  </nav>
</div>


<div class="absolute top-0 inset-x-0 p-2 transition transform origin-top-right md:hidden">
  <div class="rounded-lg shadow-md bg-white ring-1 ring-black ring-opacity-5 overflow-hidden">
    <div class="px-2 py-1 flex items-center justify-between">
      <div>
        <img class="h-auto w-auto max-h-8" src="/small_logo.png" alt="logo">
      </div>
      <div class="flex items-center justify-between" role="none">
        <a class="text-md text-blue-900 rounded py-1 px-2 hover:underline" href="/#how_it_works">How It Works</a>

        <a class="text-md text-blue-900 rounded py-1 px-2 hover:underline" href="/#pricing">Pricing</a>
      </div>
      <div class="text-right" role="none">
        <% if current_user %>
          <%= link_to current_user.email, dashboard_path, class: "text-md text-blue-900 rounded py-1 px-2 hover:underline" %>

          <%= link_to "Sign out", sign_out_path, method: :delete, class: "text-md text-blue-900 rounded py-1 px-2 hover:underline" %>
        <% else %>
          <%= link_to "Login", sign_in_path, class: "text-blue-500 border border-blue rounded py-1 px-2 border-blue-500 hover:bg-blue-500 hover:text-white hover:shadow" %>
        <%end%>
      </div>
    </div>
  </div>
</div>